export const RANDOM_PEOPLE_LIST = 'RANDOM_PEOPLE_LIST';
export const RANDOM_PEOPLE_LIST_CLEAR = 'RANDOM_PEOPLE_LIST_CLEAR';
export const RANDOM_AGE_LIST = 'RANDOM_AGE_LIST';
export const RANDOM_AGE_LIST_CLEAR = 'RANDOM_AGE_LIST_CLEAR';